"""edit user table

Revision ID: 17146466f015
Revises: 8741450b7c43
Create Date: 2026-04-22 18:43:56.000055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17146466f015'
down_revision: Union[str, None] = '8741450b7c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reminder_started_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reminder_count', sa.Integer(), nullable=False))
    op.drop_column('users', 'reminder_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reminder_sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'reminder_count')
    op.drop_column('users', 'reminder_started_at')
    # ### end Alembic commands ###
