"""add users.reminder_sent

Revision ID: 4739f3b234bf
Revises: 30b30abf67ca
Create Date: 2026-04-22 18:10:53.435389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4739f3b234bf'
down_revision: Union[str, None] = '30b30abf67ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reminder_sent', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'reminder_sent')
    # ### end Alembic commands ###
